### ISSUE TITLE
关于OctoMap

### ISSUE THREAD

**Issue by asachildofxx** [carry4985/ORB_SLAM2_MAP#1]
您好！您的这份代码让我学习了很多，非常感谢！我使用例程中的rgbd_tum.cc作为主函数进行了编译，结果成功了。在后续运行程序时，可以看到点云地图，但没有八叉树地图。我查看了代码，发现在MapDrawer.cc部分是有OctoMap相关操作的。所以想请教您，要怎样才能出现八叉树地图呢，我需要修改代码中的某些部分吗？

**Comment by asachildofxx** [comment]
您好，我又仔细学习了您的代码Viewer.cc，发现了显示八叉树地图的方法了。总之，非常感谢！

**Comment by yinhe01** [comment]
你好，能向您请教一个问题吗，我在编译的过程中出现g2o错误,作者在readme里写需要修改cmakeLists.txt，添加g2o的绝对路径，可是我不不知道该怎么修改，能否向您请假一下。
编译错误如下：
![2019-04-25 09-58-32屏幕截图](https://user-images.githubusercontent.com/35280897/56705096-24896f80-6742-11e9-95e3-67dc240d378a.png)
